/*
 * Copyright (c) 2020.
 * d3sd1.
 * All right reserved.
 * Do not re-distribute this file nor project without permission.
 */

SET search_path TO common,logging,onriot,onlol,ontft,onlor,onlwr;
INSERT INTO apiendpoint (keyname, disabled, endpoint, method, requiresapikey, riotgame_id, countsforratelimit, stub)
VALUES ('lol-champ-mastery', false,
        'https://{{hostUrl}}/lol/champion-mastery/v4/champion-masteries/by-summoner/{{encryptedSummonerId}}', 0, true,
        1,
        true,
        null),
       ('lol-champ-rotations', false, 'https://{{hostUrl}}/lol/platform/v3/champion-rotations', 0, true, 1, true, null),
       ('lol-leagues-scraper', false,
        'https://{{hostUrl}}/lol/league-exp/v4/entries/{{queue}}/{{tier}}/{{division}}?page={{page}}',
        0, true, 1, true, null),
       ('lol-summoner-leagues', false, 'https://{{hostUrl}}/lol/league/v4/entries/by-summoner/{{encryptedSummonerId}}',
        0, true, 1, true, null),
       ('lol-leagues-byid', false, 'https://{{hostUrl}}/lol/league/v4/leagues/{{leagueId}}', 0, true, 1, true, null),
       ('lol-status', false, 'https://{{hostUrl}}/lol/status/v3/shard-data', 0, true, 1, false, null),
       ('lol-match', false, 'https://{{hostUrl}}/lol/match/v4/matches/{{matchId}}', 0, true, 1, true, null),
       ('lol-matchlists', false, 'https://{{hostUrl}}/lol/match/v4/matchlists/by-account/{{encryptedAccountId}}', 0,
        true, 1, true, null),
       ('lol-match-timeline', false, 'https://{{hostUrl}}/lol/match/v4/timelines/by-match/{{matchId}}', 0, true, 1,
        true, null),
       ('lol-tournament-matches', false,
        'https://{{hostUrl}}/lol/match/v4/matches/by-tournament-code/{{tournamentCode}}/ids', 0, true, 1, true, null),
       ('lol-tournament-match-info', false,
        'https://{{hostUrl}}/lol/match/v4/matches/{matchId}/by-tournament-code/{{tournamentCode}}', 0, true, 1, true,
        null),
       ('lol-summoner-spectator', false,
        'https://{{hostUrl}}/lol/spectator/v4/active-games/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true,
        null),
       ('lol-featured-games', false, 'https://{{hostUrl}}/lol/spectator/v4/featured-games', 0, true, 1, true, null),
       ('lol-summoner-byid', false, 'https://{{hostUrl}}/lol/summoner/v4/summoners/{{encryptedSummonerId}}', 0, true, 1,
        true, null),
       ('lol-summoner-byname', false, 'https://{{hostUrl}}/lol/summoner/v4/summoners/by-name/{{summonerName}}', 0, true,
        1, true, null),
       ('lol-summoner-bypuuid', false, 'https://{{hostUrl}}/lol/summoner/v4/summoners/by-puuid/{{encryptedPUUID}}', 0,
        true, 1, true, null),
       ('lol-summoner-byaccount', false,
        'https://{{hostUrl}}/lol/summoner/v4/summoners/by-account/{{encryptedAccountId}}', 0, true, 1, true, null),
       ('tft-summoner-leagues', false, 'https://{{hostUrl}}/tft/league/v1/entries/by-summoner/{{encryptedSummonerId}}',
        0, true, 2, true, null),
       ('tft-leagues-scraper', false, 'https://{{hostUrl}}/tft/league/v1/entries/{{tier}/{division}}', 0, true, 2, true,
        null),
       ('tft-leagues-challenger', false, 'https://{{hostUrl}}/tft/league/v1/challenger', 0, true, 2, true, null),
       ('tft-leagues-grandmaster', false, 'https://{{hostUrl}}/tft/league/v1/grandmaster', 0, true, 2, true, null),
       ('tft-leagues-master', false, 'https://{{hostUrl}}/tft/league/v1/master', 0, true, 2, true, null),
       ('tft-league-byid', false, 'https://{{hostUrl}}/tft/league/v1/leagues/{{leagueId}}', 0, true, 2, true, null),
       ('tft-summoner-matches', false, 'https://{{hostUrl}}/tft/match/v1/matches/by-puuid/{{puuid}}/ids', 0, true, 2,
        true, null),
       ('tft-match', false, 'https://{{hostUrl}}/tft/match/v1/matches/{{matchId}}', 0, true, 2, true, null),
       ('tft-summoner-byaccount', false,
        'https://{{hostUrl}}/tft/summoner/v1/summoners/by-account/{{encryptedAccountId}}', 0, true, 2, true, null),
       ('tft-summoner-byname', false, 'https://{{hostUrl}}/tft/summoner/v1/summoners/by-name/{{summonerName}}', 0, true,
        2, true, null),
       ('tft-summoner-bypuuid', false, 'https://{{hostUrl}}/tft/summoner/v1/summoners/by-puuid/{{encryptedPUUID}}', 0,
        true, 2, true, null),
       ('tft-summoner-byid', false, 'https://{{hostUrl}}/tft/summoner/v1/summoners/{{encryptedSummonerId}}', 0, true, 2,
        true, null),
       ('com-verify-code', false,
        'https://{{hostUrl}}/lol/platform/v4/third-party-code/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true,
        null),
       ('lol-tournament-codes', false, 'https://{{hostUrl}}/lol/tournament/v4/codes', 1, true, 1, true,
        '{{hostUrl}}/lol/tournament-stub/v4/codes'),
       ('lol-tournament-bycode', false, 'https://{{hostUrl}}/lol/tournament/v4/codes/{{tournamentCode}}', 0, true, 1,
        true, null),
       ('lol-tournament-lobby', false, 'https://{{hostUrl}}/lol/tournament/v4/lobby-events/by-code/{{tournamentCode}}',
        0, true, 1, true,
        'https://{{hostUrl}}/lol/tournament-stub/v4/lobby-events/by-code/{{tournamentCode}}'),
       ('lol-tournament-providers', false, 'https://{{hostUrl}}/lol/tournament/v4/providers', 1, true, 1, true,
        'https://{{hostUrl}}/lol/tournament-stub/v4/providers'),
       ('lol-tournament-send', false, 'https://{{hostUrl}}/lol/tournament/v4/tournaments', 1, true, 1, true,
        'https://{{hostUrl}}/lol/tournament-stub/v4/tournaments'),
       ('ddragon-queues', false, 'http://static.developer.riotgames.com/docs/lol/queues.json', 1, false, 1, false,
        null),
       ('ddragon-maps', false, 'http://static.developer.riotgames.com/docs/lol/maps.json', 1, false, 1, false, null),
       ('ddragon-gamemodes', false, 'http://static.developer.riotgames.com/docs/lol/gameModes.json', 1, false, 1, false,
        null),
       ('ddragon-gametypes', false, 'http://static.developer.riotgames.com/docs/lol/gameTypes.json', 1, false, 1, false,
        null),
       ('ddragon-platform-realm', false, 'https://ddragon.leagueoflegends.com/realms/{{platform}}.json', 1, false, 1,
        false, null),
       ('ddragon-versions', false, 'https://ddragon.leagueoflegends.com/api/versions.json', 1, false, 1, false, null),
       ('ddragon-languages', false, 'https://ddragon.leagueoflegends.com/cdn/languages.json', 1, false, 1, false, null),
       ('ddragon-champs', false,
        'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/champion.json', 1, false, 1,
        false, null),
       ('ddragon-champ-info', false,
        'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/champion/{{championKeyName}}.json',
        1, false, 1, false, null),
       ('ddragon-items', false, 'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/item.json',
        1, false, 1,
        false, null),
       ('ddragon-summonerspells', false,
        'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/summoner.json', 1, false, 1,
        false, null),
       ('ddragon-profileicons', false,
        'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/profileicon.json', 1, false,
        1, false, null),
       ('ddragon-seasons', false, 'http://static.developer.riotgames.com/docs/lol/seasons.json', 1, false, 1, false,
        null);
