# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1-jdk-12

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B verify
          - mvn -B compile
          - mvn -B package
        services:
          - postgres
        artifacts:
          - target/**
          - src/main/resources/scripts/run-scraper.sh

    - step:
        deployment: TEST
        name: Deploy to test
        image: atlassian/default-image:2
        script:
          - "ssh $SFTP_USER@$SFTP_HOST 'pkill -9 java || echo IT_WAS_OK'"
          - "ssh $SFTP_USER@$SFTP_HOST 'rm -rf /var/www/*'"
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'target/*.jar'
              DEBUG: 'true'
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'src/main/resources/scripts/*'
              DEBUG: 'true'
          - "ssh $SFTP_USER@$SFTP_HOST touch /var/www/env.conf"
          - "ssh $SFTP_USER@$SFTP_HOST \"echo -e $SFTP_ENV >> /var/www/env.conf\""
          - "ssh $SFTP_USER@$SFTP_HOST 'chmod +x /var/www/run-scraper.sh && sh /var/www/run-scraper.sh &> /dev/null & disown'"


    - step:
        deployment: PROD
        name: Deploy to all prod servers
        trigger: manual
        image: atlassian/default-image:2
        script:
          # PROD SERVER 1
          - "ssh $SFTP_USER@$SFTP_HOST_1 'pkill -9 java || echo IT_WAS_OK'"
          - "ssh $SFTP_USER@$SFTP_HOST_1 'rm -rf /var/www/*'"
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'target/*.jar'
              DEBUG: 'true'
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'src/main/resources/scripts/*'
              DEBUG: 'true'
          - "ssh $SFTP_USER@$SFTP_HOST_1 touch /var/www/env.conf"
          - "ssh $SFTP_USER@$SFTP_HOST_1 \"echo -e $SFTP_ENV >> /var/www/env.conf\""
          - "ssh $SFTP_USER@$SFTP_HOST_1 'chmod +x /var/www/run-scraper.sh && sh /var/www/run-scraper.sh &> /dev/null & disown'"

          # PROD SERVER 2 HERE
definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'dev_onriot'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'