# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1-jdk-12

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B verify
          - mvn -B compile
          - mvn -B package
        services:
          - postgres
        artifacts:
          - target/**

    - step:
        deployment: TEST
        name: Deploy to test
        image: atlassian/default-image:2
        script:
          - "apt-get update -y"
          - "apt-get install -y ssh"
          - "ssh -t $SFTP_USER@$SFTP_HOST ls"
          - "ssh -t $SFTP_USER@$SFTP_HOST 'pkill -9 java'"
          - "ssh -T $SFTP_USER@$SFTP_HOST 'nohup java -Dspring.profiles.active=test -jar /var/www/*.jar &> /dev/null &'"
          - "ssh -T $SFTP_USER@$SFTP_HOST 'disown'"
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'target/*.jar'
              DEBUG: 'true'

    - step:
        deployment: PROD
        name: Deploy to all prod servers
        trigger: manual
        image: atlassian/default-image:2
        script:
          - "apt-get update -y"
          - "apt-get install -y ssh"
          - "ssh -T $SFTP_USER@$SFTP_HOST 'pkill -9 java'"
          - "ssh -T $SFTP_USER@$SFTP_HOST 'nohup java -Dspring.profiles.active=test -jar /var/www/*.jar &> /dev/null &'"
          - "ssh -T $SFTP_USER@$SFTP_HOST 'disown'"
          # PROD SERVER 1
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST_1
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'target/*.jar'
              DEBUG: 'true'

          # PROD SERVER 2 HERE
definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'dev_onriot'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'