# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1-jdk-12

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -Dspring.profiles.active=bitbucketpipeline -B verify
          - mvn -Dspring.profiles.active=bitbucketpipeline -B compile
          - mvn -Dspring.profiles.active=bitbucketpipeline -B package
        artifacts:
          - target/**

    - step:
        deployment: TEST
        name: Deploy to test
        image: atlassian/default-image:2
        script:
          - "apt-get update -y && apt-get install -y ssh"
          - "ssh root@167.86.78.132 \"pkill -9 java\""
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'target/*.jar' # Optional
              DEBUG: 'true'
          - "ssh root@167.86.78.132 \"java -Dspring.profiles.active=$SFTP_ENV -jar /var/www/*.jar && disown\""