# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1-jdk-12

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B verify
          - mvn -B compile
          - mvn -B package
        services:
          - postgres
        artifacts:
          - target/**
          - src/main/resources/scripts/run-scraper.sh

    - step:
        deployment: TEST
        name: Deploy to test
        image: atlassian/default-image:2
        script:
          - "ssh $SFTP_USER@$SFTP_HOST 'killall PROCESS || echo PROCESS_WAS_NOT_RUNNING'"
          - "ssh $SFTP_USER@$SFTP_HOST 'rm -rf /var/www/*'"
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'target/*.jar'
              DEBUG: 'true'
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'src/main/resources/scripts/*'
              DEBUG: 'true'
          - "ssh $SFTP_USER@$SFTP_HOST 'nohup /var/www/run-scraper.sh &> /dev/null &'"


    - step:
        deployment: PROD
        name: Deploy to all prod servers
        trigger: manual
        image: atlassian/default-image:2
        script:
          - # PROD SERVER 1
          - pipe: atlassian/ssh-run:0.2.3
            variables:
              SSH_USER: $SFTP_USER
              SERVER: $SFTP_HOST
              COMMAND: 'pkill -9 java && rm -rf /var/www/*'
              DEBUG: 'true'
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: 'target/*.jar'
              DEBUG: 'true'

          # PROD SERVER 2 HERE
definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'dev_onriot'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'