SET search_path TO common,logging,onriot,onlol,ontft,onlor,onlwr;
INSERT INTO apiendpoint (disabled, endpoint, method, requiresapikey, riotgame_id, countsforratelimit, stuburl)
VALUES (false, '/lol/champion-mastery/v4/champion-masteries/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true,
        null),
       (false, '/lol/platform/v3/champion-rotations', 0, true, 1, true, null),
       (false, '/lol/league-exp/v4/entries/{{queue}}/{{tier}}/{{division}}', 0, true, 1, true, null),
       (false, '/lol/league/v4/entries/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true, null),
       (false, '/lol/league/v4/leagues/{{leagueId}}', 0, true, 1, true, null),
       (false, '/lol/status/v3/shard-data', 0, true, 1, false, null),
       (false, '/lol/match/v4/matches/{{matchId}}', 0, true, 1, true, null),
       (false, '/lol/match/v4/matchlists/by-account/{{encryptedAccountId}}', 0, true, 1, true, null),
       (false, '/lol/match/v4/timelines/by-match/{{matchId}}', 0, true, 1, true, null),
       (false, '/lol/match/v4/matches/by-tournament-code/{{tournamentCode}}/ids', 0, true, 1, true, null),
       (false, '/lol/match/v4/matches/{matchId}/by-tournament-code/{{tournamentCode}}', 0, true, 1, true, null),
       (false, '/lol/spectator/v4/active-games/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true, null),
       (false, '/lol/spectator/v4/featured-games', 0, true, 1, true, null),
       (false, '/lol/summoner/v4/summoners/{{encryptedSummonerId}}', 0, true, 1, true, null),
       (false, '/lol/summoner/v4/summoners/by-name/{{summonerName}}', 0, true, 1, true, null),
       (false, '/lol/summoner/v4/summoners/by-puuid/{{encryptedPUUID}}', 0, true, 1, true, null),
       (false, '/lol/summoner/v4/summoners/by-account/{{encryptedAccountId}}', 0, true, 1, true, null),
       (false, '/tft/league/v1/entries/by-summoner/{{encryptedSummonerId}}', 0, true, 2, true, null),
       (false, '/tft/league/v1/entries/{{tier}/{division}}', 0, true, 2, true, null),
       (false, '/tft/league/v1/challenger', 0, true, 2, true, null),
       (false, '/tft/league/v1/grandmaster', 0, true, 2, true, null),
       (false, '/tft/league/v1/master', 0, true, 2, true, null),
       (false, '/tft/league/v1/leagues/{{leagueId}}', 0, true, 2, true, null),
       (false, '/tft/match/v1/matches/by-puuid/{{puuid}}/ids', 0, true, 2, true, null),
       (false, '/tft/match/v1/matches/{{matchId}}', 0, true, 2, true, null),
       (false, '/tft/summoner/v1/summoners/by-account/{{encryptedAccountId}}', 0, true, 2, true, null),
       (false, '/tft/summoner/v1/summoners/by-name/{{summonerName}}', 0, true, 2, true, null),
       (false, '/tft/summoner/v1/summoners/by-puuid/{{encryptedPUUID}}', 0, true, 2, true, null),
       (false, '/tft/summoner/v1/summoners/{{encryptedSummonerId}}', 0, true, 2, true, null),
       (false, '/lol/platform/v4/third-party-code/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true, null),
       (false, '/lol/tournament/v4/codes', 1, true, 1, true, '/lol/tournament-stub/v4/codes'),
       (false, '/lol/tournament/v4/codes/{{tournamentCode}}', 0, true, 1, true, null),
       (false, '/lol/tournament/v4/codes/{{tournamentCode}}', 2, true, 1, true, null),
       (false, '/lol/tournament/v4/lobby-events/by-code/{{tournamentCode}}', 0, true, 1, true,
        '/lol/tournament-stub/v4/lobby-events/by-code/{{tournamentCode}}'),
       (false, '/lol/tournament/v4/providers', 1, true, 1, true, '/lol/tournament-stub/v4/providers'),
       (false, '/lol/tournament/v4/tournaments', 1, true, 1, true, '/lol/tournament-stub/v4/tournaments');