SET search_path TO common,logging,onriot,onlol,ontft,onlor,onlwr;
INSERT INTO apiendpoint (disabled, endpoint, method, requiresapikey, riotgame_id, countsforratelimit)
VALUES (false, '/lol/champion-mastery/v4/champion-masteries/by-summoner/{{encryptedSummonerId}}', 'GET', true, 1, true),
       (false, '/lol/platform/v3/champion-rotations', 'GET', true, 1, true),
       (false, '/lol/league-exp/v4/entries/{{queue}}/{{tier}}/{{division}}', 'GET', true, 1, true),
       (false, '/lol/league/v4/entries/by-summoner/{{encryptedSummonerId}}', 'GET', true, 1, true),
       (false, '/lol/league/v4/leagues/{{leagueId}}', 'GET', true, 1, true),
       (false, '/lol/status/v3/shard-data', 'GET', true, 1, false),
       (false, '/lol/match/v4/matches/{{matchId}}', 'GET', true, 1, true),
       (false, '/lol/match/v4/matchlists/by-account/{{encryptedAccountId}}', 'GET', true, 1, true),
       (false, '/lol/match/v4/timelines/by-match/{{matchId}}', 'GET', true, 1, true),
       (false, '/lol/match/v4/matches/by-tournament-code/{{tournamentCode}}/ids', 'GET', true, 1, true),
       (false, '/lol/match/v4/matches/{matchId}/by-tournament-code/{{tournamentCode}}', 'GET', true, 1, true),
       (false, '/lol/spectator/v4/active-games/by-summoner/{{encryptedSummonerId}}', 'GET', true, 1, true),
       (false, '/lol/spectator/v4/featured-games', 'GET', true, 1, true),
       (false, '/lol/summoner/v4/summoners/{{encryptedSummonerId}}', 'GET', true, 1, true),
       (false, '/lol/summoner/v4/summoners/by-name/{{summonerName}}', 'GET', true, 1, true),
       (false, '/lol/summoner/v4/summoners/by-puuid/{{encryptedPUUID}}', 'GET', true, 1, true),
       (false, '/lol/summoner/v4/summoners/by-account/{{encryptedAccountId}}', 'GET', true, 1, true),
       (false, '/tft/league/v1/entries/by-summoner/{{encryptedSummonerId}}', 'GET', true, 2, true),
       (false, '/tft/league/v1/entries/{{tier}/{division}}', 'GET', true, 2, true),
       (false, '/tft/league/v1/challenger', 'GET', true, 2, true),
       (false, '/tft/league/v1/grandmaster', 'GET', true, 2, true),
       (false, '/tft/league/v1/master', 'GET', true, 2, true),
       (false, '/tft/league/v1/leagues/{{leagueId}}', 'GET', true, 2, true),
       (false, '/tft/match/v1/matches/by-puuid/{{puuid}}/ids', 'GET', true, 2, true),
       (false, '/tft/match/v1/matches/{{matchId}}', 'GET', true, 2, true),
       (false, '/tft/summoner/v1/summoners/by-account/{{encryptedAccountId}}', 'GET', true, 2, true),
       (false, '/tft/summoner/v1/summoners/by-name/{{summonerName}}', 'GET', true, 2, true),
       (false, '/tft/summoner/v1/summoners/by-puuid/{{encryptedPUUID}}', 'GET', true, 2, true),
       (false, '/tft/summoner/v1/summoners/{{encryptedSummonerId}}', 'GET', true, 2, true),
       (false, '/lol/platform/v4/third-party-code/by-summoner/{{encryptedSummonerId}}', 'GET', true, 1, true),
       (false, '/lol/tournament/v4/codes', 'POST', true, 1, true),
       (false, '/lol/tournament/v4/codes/{{tournamentCode}}', 'GET', true, 1, true),
       (false, '/lol/tournament/v4/codes/{{tournamentCode}}', 'PUT', true, 1, true),
       (false, '/lol/tournament/v4/lobby-events/by-code/{{tournamentCode}}', 'GET', true, 1, true),
       (false, '/lol/tournament/v4/providers', 'POST', true, 1, true),
       (false, '/lol/tournament/v4/tournaments', 'POST', true, 1, true);