SET search_path TO common,logging,onriot,onlol,ontft,onlor,onlwr;
INSERT INTO apiendpoint (disabled, endpoint, method, requiresapikey, riotgame_id, countsforratelimit, stub)
VALUES (false, '{{hostUrl}}/lol/champion-mastery/v4/champion-masteries/by-summoner/{{encryptedSummonerId}}', 0, true, 1,
        true,
        null),
       (false, '{{hostUrl}}/lol/platform/v3/champion-rotations', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/league-exp/v4/entries/{{queue}}/{{tier}}/{{division}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/league/v4/entries/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/league/v4/leagues/{{leagueId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/status/v3/shard-data', 0, true, 1, false, null),
       (false, '{{hostUrl}}/lol/match/v4/matches/{{matchId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/match/v4/matchlists/by-account/{{encryptedAccountId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/match/v4/timelines/by-match/{{matchId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/match/v4/matches/by-tournament-code/{{tournamentCode}}/ids', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/match/v4/matches/{matchId}/by-tournament-code/{{tournamentCode}}', 0, true, 1, true,
        null),
       (false, '{{hostUrl}}/lol/spectator/v4/active-games/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/spectator/v4/featured-games', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/summoner/v4/summoners/{{encryptedSummonerId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/summoner/v4/summoners/by-name/{{summonerName}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/summoner/v4/summoners/by-puuid/{{encryptedPUUID}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/summoner/v4/summoners/by-account/{{encryptedAccountId}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/tft/league/v1/entries/by-summoner/{{encryptedSummonerId}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/league/v1/entries/{{tier}/{division}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/league/v1/challenger', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/league/v1/grandmaster', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/league/v1/master', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/league/v1/leagues/{{leagueId}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/match/v1/matches/by-puuid/{{puuid}}/ids', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/match/v1/matches/{{matchId}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/summoner/v1/summoners/by-account/{{encryptedAccountId}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/summoner/v1/summoners/by-name/{{summonerName}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/summoner/v1/summoners/by-puuid/{{encryptedPUUID}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/tft/summoner/v1/summoners/{{encryptedSummonerId}}', 0, true, 2, true, null),
       (false, '{{hostUrl}}/lol/platform/v4/third-party-code/by-summoner/{{encryptedSummonerId}}', 0, true, 1, true,
        null),
       (false, '{{hostUrl}}/lol/tournament/v4/codes', 1, true, 1, true, '{{hostUrl}}/lol/tournament-stub/v4/codes'),
       (false, '{{hostUrl}}/lol/tournament/v4/codes/{{tournamentCode}}', 0, true, 1, true, null),
       (false, '{{hostUrl}}/lol/tournament/v4/codes/{{tournamentCode}}', 2, true, 1, true, null),
       (false, '{{hostUrl}}/lol/tournament/v4/lobby-events/by-code/{{tournamentCode}}', 0, true, 1, true,
        '{{hostUrl}}/lol/tournament-stub/v4/lobby-events/by-code/{{tournamentCode}}'),
       (false, '{{hostUrl}}/lol/tournament/v4/providers', 1, true, 1, true,
        '{{hostUrl}}/lol/tournament-stub/v4/providers'),
       (false, '{{hostUrl}}/lol/tournament/v4/tournaments', 1, true, 1, true,
        '{{hostUrl}}/lol/tournament-stub/v4/tournaments'),
       (false, 'http://static.developer.riotgames.com/docs/lol/queues.json', 1, false, 1, false, null),
       (false, 'http://static.developer.riotgames.com/docs/lol/queues.json', 1, false, 1, false, null),
       (false, 'http://static.developer.riotgames.com/docs/lol/maps.json', 1, false, 1, false, null),
       (false, 'http://static.developer.riotgames.com/docs/lol/gameModes.json', 1, false, 1, false, null),
       (false, 'http://static.developer.riotgames.com/docs/lol/gameTypes.json', 1, false, 1, false, null),
       (false, 'https://ddragon.leagueoflegends.com/realms/{{platform}}.json', 1, false, 1, false, null),
       (false, 'https://ddragon.leagueoflegends.com/api/versions.json', 1, false, 1, false, null),
       (false, 'https://ddragon.leagueoflegends.com/cdn/languages.json', 1, false, 1, false, null),
       (false, 'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/champion.json', 1, false, 1,
        false, null),
       (false,
        'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/champion/{{championKeyName}}.json',
        1, false, 1, false, null),
       (false, 'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/item.json', 1, false, 1,
        false, null),
       (false, 'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/summoner.json', 1, false, 1,
        false, null),
       (false, 'http://ddragon.leagueoflegends.com/cdn/{{versionNumber}}/data/{{language}}/profileicon.json', 1, false,
        1, false, null),
       (false, 'http://static.developer.riotgames.com/docs/lol/seasons.json', 1, false, 1, false, null);
